
import { useEffect} from "react";
import Footer from "../components/footer/footer.jsx"
import Navigator from "../components/navigator.jsx"
import { useLocation } from "react-router-dom";

import spiral_img from '/done.png'

function Home(){
   const location = useLocation();

   useEffect(() => {
      window.scrollTo({ top: 0});
   }, [location.pathname]);

   return(
      <>
         <main className="max-w-[1100px] mx-auto relative mb-10">

            <section className="w-full z-10 relative overflow-hidden p-4">
               
               <img className="spiral-animation h-[30rem] select-none min-w-min absolute opacity-[var(--img-opa)] left-1/2 transform -translate-x-1/2" src={spiral_img} alt="" />
               <h1 className="mt-[5rem] text-[var(--text-clr)] text-[3rem]">Home</h1>
               <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab id saepe eum repellat doloribus modi enim iste ipsa corrupti dignissimos?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
               <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, ab. Earum sequi voluptates expedita neque reiciendis labore ullam dolor distinctio illo cumque voluptate quas architecto debitis doloribus, vitae quo quis id minima perferendis fugit hic consequatur dolorum quibusdam! Amet hic unde repellendus suscipit recusandae mollitia exercitationem ratione nesciunt, quae fuga natus ipsam cupiditate sit itaque quos atque quo dolore ea aliquam voluptates. Aperiam doloribus laudantium possimus provident, non animi soluta maxime veritatis illo odio ab quas sed iusto similique corporis rem neque quod, minus, ullam deleniti voluptates facere dolorum consequatur? Repudiandae quis maxime quisquam assumenda labore eligendi voluptatibus deleniti at?</p>
            
            </section>

            <div className="sticky max-[990px]:w-full w-fit max-[990px]:left-auto left-[50%] max-[990px]:translate-x-0 transform translate-x-[-50%] z-20 bottom-5">
               <Navigator active="home"/>
            </div>
            
         </main>
         <Footer />
      </>
   )
}

export default Home